### ISSUE TITLE
Aviation Obstacle Documentation

### ISSUE THREAD

**Issue by ThomasRanvikEriksen** [3lbits/CIM4NoUtility#347]
1. Add how to use the Name Classes
2. Explanation for all the extensions
3. A better mapping between CIM and Kartverket
4. Add documentation for nc-no namespace
5. Add StructureSupport

Lastely check if the example file is compliant with the documentation

**Comment by EmilieSkog** [comment]
The commit  9efc5b9 solves the following

>- [x] 1. Add how to use the Name Classes
>- [x] 2. Explanation for all the extensions
>- [x] 3. A better mapping between CIM and Kartverket
>- [x] 4. Add documentation for nc-no namespace
>- [ ] 5. Add StructureSupport
> 
>- [ ] Lastely check if the example file is compliant with the documentation

The documentation can be found in Telemark-120/docs/AviationObstacleReporting.adoc

**Comment by EmilieSkog** [comment]
Header URI's are covered in #349
